name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: windows-latest # ubuntu-latest
      steps:
      #- uses: actions/checkout@v2
      #- name: install cppunit
      #run: sudo apt install -y libcppunit-dev
      #- name: configure
      #run: ./configure
      #- name: make
      #run: make
      #- name: make test
      #run: make test
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@latest
      - name: Install GCC
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac
        uses: egor-tensin/setup-gcc@v1
      - name: Build Server
        run: ./build-server.bat
        #run: ./run-server.bat
