# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - lorenz-ctf

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Install GCC
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac
        uses: egor-tensin/setup-gcc@v1
        with:
          # GCC version to install
          #version: # optional, default is latest
          # Target platform
          platform: x86 # optional, default is x64
          # Install Cygwin packages
          #cygwin: # optional, default is 0
          # Set up cc/gcc/c++/g++ executables
          #cc: # optional, default is 1
          # On Cygwin, replace executable symlinks with hardlinks
          #hardlinks: # optional, default is 0
    
      - name: Build with G++
        run: build-server.bat

      #- name: dotnet publish
       # run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ws-game-server #.net-app
          path: ${{env.DOTNET_ROOT}}/ws-game-server.exe # myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ws-game-server # .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lorenz-ctf'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AD329E3527C2409EAD03BA4BCE3E38B2 }}
          package: .
